name: elcare_application
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  custom_timer: ^0.0.6
  light: ^2.1.0
  flutter_dnd: ^0.1.3
  flutter_awesome_alert_box: ^2.1.1
  flutter_ringtone_player: ^3.1.0
  
  path: ^1.8.0
  flutter_phone_direct_caller: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_dialpad: ^1.0.1
  charts_flutter: ^0.12.0
  slide_digital_clock: ^1.0.2
  get: ^4.5.1
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  cupertino_icons: ^1.0.2
  flutter_facebook_auth: ^3.5.2
  google_sign_in: ^5.1.1
  provider: ^6.0.1
  shared_preferences: ^2.0.9

  flutter_form_builder: ^7.0.0
  image_picker: ^0.8.4+4
  flutter_switch: ^0.3.2
  sqflite: ^2.0.0+4

  # store image
  path_provider: ^2.0.1


  android_alarm_manager: ^2.0.2
  
  audioplayers: ^0.20.1
  flutter_local_notifications: ^9.1.4
  rxdart: ^0.27.3

  dcdg: ^4.0.0



  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  hive_generator: ^1.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/images/background.jpg
    - assets/fonts/images/logo.png
    - assets/fonts/images/regular_user_back.jpg
    - assets/fonts/images/pilltimebutton.png
    - assets/fonts/images/sleeptrackerbutton.png
    - assets/fonts/images/profilebutton.png
    - assets/fonts/images/loginback.jpg
    - assets/Medical_resized.png
    - assets/personal resized.png
    - assets/alarm_sound.mp3
    - assets/Australia.png
    - assets/Metallic Beeps.mp3
    - assets/notification.mp3
    - assets/pill.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist.TTF
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
